apiVersion: v1
kind: pod
metadata: 
  labels: 
    app: demo-voting-app
    name: voting-app-pod
  name: voting-app-pod
spec: 
  containers: 
    - 
      image: dockersamples/examplevotingapp_vote
      name: voting-app
      ports: 
        - 
          containerPort: 80
